### ISSUE TITLE
Profile xxxxx not found

### ISSUE THREAD

**Issue by VAdamec** [projectcalico/calico-dcos#45]
Hi, I just follow this example https://www.projectcalico.org/calico-dcos-demo-security-speed-and-no-more-port-forwarding/ and getting stuck on profile settings via calicoctl. 

```
calicoctl profile database-net rule show

Profile database-net not found.
```

can you please advice ? Via UI and docker all seems to be correctly setup.

https://slack-files.com/T0BC4L1GD-F3LBYRG6S-98b55e3401

Based on discussion on Slack ```https://calicousers.slack.com/messages/mesos/``` there is possible issue in version (0.22.0) bundled by dc/os package, but this was not validated yet (i'll test it without dc/os package and give you know).

**Comment by caseydavenport** [comment]
Closing as this is quite old.
